version: '3'
services:
  database:
    hostname: database
    build: database/.
    ports:
      - "3306:3306"
    networks:
      - network
  app:
    build: app/.
    ports:
      - "80:80"
    depends_on:
      - "database"
    networks:
      - network
networks:
  network:
    driver: bridge
